GestorC/GestorC/Controllers/PCController.cs
using GestorC.Models;
using GestorC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestorC.Controllers
{
    public class PCController : Controller
    {
        // GET: PC
        [HttpGet]
        public ActionResult Index()
        {
            Proxy prox = UberController.Instance.getProxy(Session["current"] as string);
            return View(new VM_Secretaria() { proxy = prox });
        }

        [HttpGet]
        public ActionResult PrevioAgenda(string sesion)
        {
            Proxy prox = UberController.Instance.getProxy(Session["current"] as string);
            return View(new VM_Secretaria() { proxy = prox , sesionSeleccionada = UberController.Instance.getControlador().getSesion(sesion) });
            //return Content("previo");
        }

        [HttpGet]
        public ActionResult AgregarPunto(string id, string sess)
        {
            Proxy prox = UberController.Instance.getProxy(Session["current"] as string);
            prox.aceptarSolicitud(int.Parse(id));
            return RedirectToAction("PrevioAgenda", new { sesion = sess });
        }

        [HttpGet]
        public ActionResult EliminarPunto(string id, string sess)
        {
            Proxy prox = UberController.Instance.getProxy(Session["current"] as string);
            prox.eliminarSolicitud(int.Parse(id));
            return RedirectToAction("PrevioAgenda", new { sesion = sess });
        }

        [HttpGet]
        public ActionResult IniciarSesion(string sess)
        {
            Proxy prox = UberController.Instance.getProxy(Session["current"] as string);
            //prox.eliminarSolicitud(int.Parse(id));
            prox.iniciarSesion(sess);
            return RedirectToAction("Index");
        }
    }
}

GestorC/GestorC/Views/PC/Index.cshtml
@model GestorC.ViewModels.VM_Secretaria
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/SecretariaLayout.cshtml";
}

<div class="blue">
    <h4><span class="glyphicon glyphicon-hand-right"></span> Home</h4>
</div>
<h1 class="francois blue">Bienvenido al gestor de sesiones de consejo</h1>

<hr />

<div class="row">
    <div class="col-sm-12">
        <label>Historial de sesiones</label>
        <ul class="list-group small-size-input">
            @foreach (var s in Model.GetUberController().getControlador().getAllNumeroSesiones())
            {
                if (Model.GetUberController().getControlador().getSesion(s).Estado == null)
                {
                    <li class="list-group-item"><a href="@Url.Action("PrevioAgenda", "PC", new { sesion = s})">@s</a><span class="badge blue-bg">Creada</span></li>
                }
                else if (Model.GetUberController().getControlador().getSesion(s).Estado.Value)
                {
                    <li class="list-group-item">@s<span class="badge red-bg">Cerrada</span></li>
                }
                else
                {
                    <li class="list-group-item"><span class="badge green-bg">Abierta</span></li>
                }
            }
        </ul>
    </div>
</div>

GestorC/GestorC/Views/PC/PrevioAgenda.cshtml
@model GestorC.ViewModels.VM_Secretaria
@{
    ViewBag.Title = "PrevioAgenda";
    Layout = "~/Views/Shared/SecretariaLayout.cshtml";
}

<div class="blue">
    <h4><span class="glyphicon glyphicon-hand-right"></span> @Model.sesionSeleccionada.Numero > selección de puntos</h4>
</div>
<h1 class="francois blue">Puntos para la sesión @Model.sesionSeleccionada.Numero</h1>
<a href="@Url.Action("IniciarSesion", "PC", new { sess = Model.sesionSeleccionada.Numero})">Click acá para iniciar la sesión</a>
<hr />

<div class="row">
    @if (!Model.GetUberController().getControlador().getSolicitudes().Any())
    {
        <h1 class="col-sm-6">No hay solicitudes de puntos</h1>
    }
    else
    {
        <div class="col-sm-6">
            <table class="table">
                <thead>
                    <tr class="th-header">
                        <th class="float-left">Nombre</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var p in Model.GetUberController().getControlador().getSolicitudes())
                {
                        <tr>
                            <td class="float-left">@p.Nombre</td>
                            <td class="float-center"><a href="@Url.Action("AgregarPunto", "PC", new { id = p.Id_punto.ToString(), sess = Model.sesionSeleccionada.Numero})">Agregar</a></td>
                            <td class="float-right"><a href="@Url.Action("EliminarPunto", "PC", new { id = p.Id_punto.ToString(), sess = Model.sesionSeleccionada.Numero})">Eliminar</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }


    <!-- puntos -->
    @if (!Model.sesionSeleccionada.Agenda.Any())
    {
        <h1 class="col-sm-6">No hay puntos en la agenda @Model.sesionSeleccionada.Numero</h1>
    }
    else
    {
        <div class="col-sm-6">
            <table class="table">
                <thead>
                    <tr class="th-header">
                        <th class="float-left">Nombre</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var p in Model.sesionSeleccionada.Agenda)
                    {
                        <tr>
                            <td class="float-left">@p.Nombre</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
</div>